// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szzdfxetrydgnrnugvrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6emRmeGV0cnlkZ25ybnVndnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzUxNjgsImV4cCI6MjA2NzExMTE2OH0.9ST993vyVGube01SgncQ8xRJKVGY4EDS-tFjZPoivpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});